# Generated by Django 4.2.1 on 2023-05-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('fam', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('pasport_seriya', models.CharField(max_length=9)),
                ('manzil', models.CharField(max_length=150)),
                ('navbat', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qavat', models.CharField(max_length=10)),
                ('raqami', models.SmallIntegerField()),
                ('joylar_soni', models.SmallIntegerField()),
                ('turi', models.CharField(choices=[('Lux', 'Lux'), ('Odatiy', 'Odatiy')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Xulosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(max_length=50)),
                ('xulosa', models.TextField()),
                ('sana', models.DateTimeField()),
                ('kim_tomonidan', models.CharField(max_length=100)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.bemor')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.BigIntegerField()),
                ('sana', models.DateTimeField(auto_now=True)),
                ('turi', models.CharField(blank=True, choices=[('Naqd', 'Naqd'), ('Plastic', 'Plastic')], max_length=50)),
                ('tolandi', models.BooleanField()),
                ('maqsadi', models.CharField(max_length=100)),
                ('izoh', models.TextField(blank=True)),
                ('kun_soni', models.SmallIntegerField(default=1)),
                ('bemor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.bemor')),
            ],
        ),
        migrations.CreateModel(
            name='Joylashtirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelish_sanasi', models.DateField(auto_now=True)),
                ('ketish_sanasi', models.DateField(blank=True)),
                ('qarovchi', models.BooleanField()),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.bemor')),
                ('xona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.xona')),
            ],
        ),
    ]
