# Generated by Django 4.2.1 on 2023-05-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemor',
            name='navbat',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tolov',
            name='kun_soni',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tolov',
            name='summa',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='xona',
            name='joylar_soni',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='xona',
            name='qavat',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='xona',
            name='raqami',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
