# Generated by Django 4.2.1 on 2023-05-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_bemor_navbat_alter_tolov_kun_soni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joylashtirish',
            name='kelish_sanasi',
            field=models.DateField(),
        ),
    ]
