# Generated by Django 4.2.1 on 2023-05-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_tolov_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='kun_soni',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
